### ISSUE TITLE
Home ("Elevator Pitch" page)

### ISSUE THREAD

**Issue by kevinmershon** [mershon-enterprises/website#1]
## Home (“Elevator Pitch” page)
- [x] Logo
- [x] Tagline: _"A Bakersfield software company. A name you know, a team you can count on."_
- [x] grid of "marketing" bullets from current ngBoilerplate template

Any other pertinent info?

**Comment by kevinmershon** [comment]
@devleorepo Clicking the "See what we've done" button from the home page doesn't update the navbar correctly.

**Comment by devinleonhart** [comment]
@kevinmershon Should now be fixed in https://github.com/mershon-enterprises/website/commit/f30a09f
