### ISSUE TITLE
Artifact popping / slow load on all devices

### ISSUE THREAD

**Issue by kevinmershon** [mershon-enterprises/website#12]
It's really common to see the following, before the site has completely loaded. Can we use a global on-ready to prevent it?

![screenshot_2015-05-01-14-23-40](https://cloud.githubusercontent.com/assets/812577/7437619/d0942f96-f00d-11e4-9b45-1c5194184668.png)

**Comment by kevinmershon** [comment]
It looks like a big part of the problem is that cdnify isn't having any effect. All the dependencies are being bundled into vendor.js, which is 269K minified and takes almost 900 ms to download

**Comment by devinleonhart** [comment]
Resolved as of 9215ad058003fe9c56086cd09f2bd0e4649f3e1a
