### ISSUE TITLE
Learn More ("About Us" page)

### ISSUE THREAD

**Issue by kevinmershon** [mershon-enterprises/website#2]
- [x] Picture and 1-2 paragraph bio of Kevin
- [x] Description of team size and skill set composition
- [x] Description of project administrative controls
- [x] Benefits of a virtual company
- [x] Coworking and Bakersfield Mesh
- [x] Pricing Info

**Comment by devinleonhart** [comment]
@kevinmershon I'm starting on this section next. I'll need lots of content from you, I imagine. Your bio and picture for one. And I'll need the company pricing info as well as what you mean by co-working and Bakersfield Mesh.

**Comment by devinleonhart** [comment]
@kevinmershon Well... pretty much all of it. `</helpful>`

**Comment by kevinmershon** [comment]
@Ezrael2979 I'd like to have a section on the `Learn More` page about how we do project controls. Just a couple sentences in your own words would be appreciated.

**Comment by Ezrael2979** [comment]
@kevinmershon No problem, I'll put something together.

**Comment by kevinmershon** [comment]
Here's a couple photos with me that could all be decent potentials to go on the website https://drive.google.com/folderview?id=0B5oGGFuNLHN-OUZGWmdHWDhfSFk&usp=sharing

**Comment by kevinmershon** [comment]
If it's cool with everyone, I'd still like to have links to at least the GitHub pages for each other developer in the company. We don't have to do full bios and pictures unless you really want them, but I'm not against the idea either.

**Comment by kevinmershon** [comment]
I'm not sure how exactly you want me to fill in my bio, because you're using a loop on github users. Thoughts?

**Comment by devinleonhart** [comment]
@kevinmershon That... was a pretty dumb move on my part. It should be fixed in https://github.com/mershon-enterprises/website/commit/d2e4ab4
