### ISSUE TITLE
Blogger Integration

### ISSUE THREAD

**Issue by devinleonhart** [mershon-enterprises/website#7]
Once a blogspot account has been created and its been populated with our first article, hit up the [blogger api](https://developers.google.com/blogger/) and integrate the ability to view our blogs on the `#/blog` view. 

Must be able to view the latest blog immediately upon visiting the route. 
Must be able to see an archive of blog posts, up to the last 5.
Must have link to blogger itself for "Browse Archives"

**Comment by kevinmershon** [comment]
@devinleonhart Blogspot account has been created at http://mershon-enterprises.blogspot.com/

**Comment by kevinmershon** [comment]
I just pointed it to http://blog.mershon.enterprises instead
