### ISSUE TITLE
Mail Server

### ISSUE THREAD

**Issue by devinleonhart** [mershon-enterprises/website#9]
We currently have a php-based contact form that utilizes `@mail` We need a mail server on the MEC server that will allow this to work. 

The contact form at staging.mershon.enterprises is hooked up to POST to contact.php, if you'd like to test if the mail server is set up correctly, but this php file hasn't been tested yet so it's unreliable.

**Comment by kevinmershon** [comment]
The mail server is setup and tested as working. The contact form just needs set up to work with it.
